# Features for a single object cluster

Header header

geometry_msgs/Transform transform

RawPtCldInfo rawInfo
OrientedBoundingBox obb

bool setColorHist            # Flag to state if hs_hist was computed and set
ColorHist hs_hist

bool setShapeHist            # Flag to state if shape_hist was computed and set
ShapeHist shape_hist

bool setViewpointHist        # Flag to state if view_hist was computed and set
ViewpointHist view_hist

bool setOtherFeatures        # Flag to state if other features were computed and set
OtherFeatures other
